# Basic dependabot.yml file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part1/anecdotes/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part1/course-info/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part1/notes/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part1/unicafe/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part2/collection-and-modules/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part2/course-info/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part2/phone-book/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part2/server-data/"
    # Check the npm registry for updates
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part3/backend/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part3/phonebook-backend/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/part4/blog-list/"
    schedule:
      interval: "monthly"
